tinyMCE.addI18n('es.advimage_dlg',{
tab_general:"General",
tab_appearance:"Apariencia",
tab_advanced:"Avanzado",
general:"General",
title:"Titulo",
preview:"Vista Previa",
constrain_proportions:"Proposiciones de Restriccion",
langdir:"Direccón de Lenguaje",
langcode:"Código de Lenguaje",
long_desc:"Enlace a descripción larga",
style:"Estilo",
classes:"Clases",
ltr:"Izquierda a Derecha",
rtl:"Derecha a Izquierda",
id:"Id",
map:"Mapa de Imagen",
swap_image:"Cambiar imagen",
alt_image:"Imagen Alternativa",
mouseover:"para mouseover",
mouseout:"para mouseout",
misc:"Miscelaneo",
example_img:"Imagen de apariencia previa",
missing_alt:"Esta seguro que desea continuar sin una descripción de imagen, sin la misma la imagen no podrá ser percibida por ciertos usuarios con discpacidades",
dialog_title:"Insertar/editar Imagen",
src:"URL de la imagen",
alt:"Descipción de la Imagen",
list:"Lista de Imagenes",
border:"Borde",
dimensions:"Dimensiones",
vspace:"Espacio vertical",
hspace:"Espacio Horizontal",
align:"Alineación",
align_baseline:"Linea de Base",
align_top:"Arriba",
align_middle:"Medio",
align_bottom:"Abajo",
align_texttop:"Texto Arriba",
align_textbottom:"Texto Abajo",
align_left:"Izquierda",
align_right:"Derecha",
image_list:"Lista de Imagenes"
});